# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(651, 751)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background: #F5F7FA;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(30)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.contentArea = QtWidgets.QWidget(self.centralwidget)
        self.contentArea.setStyleSheet("QWidget {\n"
"    background-color: #F5F7FA;\n"
"}")
        self.contentArea.setObjectName("contentArea")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.contentArea)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelTitle = QtWidgets.QLabel(self.contentArea)
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR")
        font.setPointSize(20)
        self.labelTitle.setFont(font)
        self.labelTitle.setStyleSheet("QWidget {font-size: 20.4pt;\n"
"letter-spacing: -1px;\n"
"line-height: 25px;\n"
"text-transform: uppercase;\n"
"color: #2f2f2e;\n"
"font-family: \"Noto Sans KR\";\n"
"qproperty-alignment: AlignCenter;\n"
"}")
        self.labelTitle.setObjectName("labelTitle")
        self.horizontalLayout_6.addWidget(self.labelTitle)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(30, 10, 30, 10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textSpecs = QtWidgets.QTextEdit(self.contentArea)
        self.textSpecs.setStyleSheet("QTextEdit {\n"
"    background-color: #F5F7FA;   \n"
"    border: none;                   /* 테두리 제거 */\n"
"    outline: none;                  /* 포커스 아웃라인 제거(일부 스타일) */\n"
"}\n"
"\n"
"QTextEdit::viewport {\n"
"    background-color: #F5F7FA;  \n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"    border: none;\n"
"    outline: none;\n"
"}")
        self.textSpecs.setLineWrapColumnOrWidth(0)
        self.textSpecs.setObjectName("textSpecs")
        self.verticalLayout_3.addWidget(self.textSpecs)
        self.labelComment = QtWidgets.QLabel(self.contentArea)
        self.labelComment.setStyleSheet("QWidget {font-size: 9.6pt;\n"
"letter-spacing: -1px;\n"
"line-height: 20px;\n"
"text-transform: uppercase;\n"
"color: #2f2f2e;\n"
"font-family: \"Noto Sans KR\";\n"
"}")
        self.labelComment.setAlignment(QtCore.Qt.AlignCenter)
        self.labelComment.setObjectName("labelComment")
        self.verticalLayout_3.addWidget(self.labelComment)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.btnCopySpecs = QtWidgets.QPushButton(self.contentArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCopySpecs.sizePolicy().hasHeightForWidth())
        self.btnCopySpecs.setSizePolicy(sizePolicy)
        self.btnCopySpecs.setStyleSheet("QPushButton {\n"
"    letter-spacing: -1px;\n"
"    line-height: 20px;\n"
"    text-transform: uppercase;\n"
"    padding: 12px 14px;\n"
"\n"
"    background-color: #F5F7FA;  \n"
"    color: #024093;                 \n"
"    border: 1.5px solid #024093;     /* 핵심 ② */\n"
"    border-radius: 6px;              /* 있으면 훨씬 안정적 */\n"
"\n"
"    padding: 6px 12px;\n"
"    font-size: 12pt;\n"
"    font-weight: 0;\n"
"    font-family: \"Noto Sans KR\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(75, 123, 236, 0.08);  /* 핵심 ③ */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(75, 123, 236, 0.18);  /* 핵심 ④ */\n"
"}")
        self.btnCopySpecs.setObjectName("btnCopySpecs")
        self.horizontalLayout_7.addWidget(self.btnCopySpecs)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 15)
        self.horizontalLayout_7.setStretch(2, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout_5.setStretch(0, 2)
        self.verticalLayout_5.setStretch(1, 7)
        self.verticalLayout_5.setStretch(2, 1)
        self.horizontalLayout_4.addWidget(self.contentArea)
        self.horizontalLayout_4.setStretch(0, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 651, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelTitle.setText(_translate("MainWindow", "PC 사양 확인 프로그램"))
        self.textSpecs.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'맑은 고딕\';\"><br /></p></body></html>"))
        self.labelComment.setText(_translate("MainWindow", "※ PC 환경에 따라 OS에서 제공되지 않는 일부 사양 정보는 표시되지 않을 수 있습니다."))
        self.btnCopySpecs.setText(_translate("MainWindow", "PC 사양 복사"))
